### ISSUE TITLE
KafkaStreams is not running. State is ERROR.

### ISSUE THREAD

**Issue by survivant** [survivant/kafkastream-statestore-migrated-to-another-instance#1]
Application logs at startup. (see next comment)

logs when I try to get : http://localhost:8282/kafka/getInteractiveQueryCount

````
2021-05-17 18:08:40.035 ERROR 18012 --- [nio-8282-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: KafkaStreams is not running. State is ERROR.] with root cause

java.lang.IllegalStateException: KafkaStreams is not running. State is ERROR.
	at org.apache.kafka.streams.KafkaStreams.validateIsRunningOrRebalancing(KafkaStreams.java:314) ~[kafka-streams-2.6.0.jar:na]
	at org.apache.kafka.streams.KafkaStreams.store(KafkaStreams.java:1207) ~[kafka-streams-2.6.0.jar:na]
	at org.apache.kafka.streams.KafkaStreams.store(KafkaStreams.java:1194) ~[kafka-streams-2.6.0.jar:na]
	at com.example.kafkaeventalarm.stream.KafkaStreamOrderProcessor.getInteractiveQueryCount(KafkaStreamOrderProcessor.java:83) ~[classes/:na]
	at com.example.kafkaeventalarm.controller.KafkaPOCController.getInteractiveQueryCount(KafkaPOCController.java:75) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626) ~[tomcat-embed-core-9.0.41.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.41.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar:5.3.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar:5.3.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar:5.3.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]

````

**Comment by survivant** [comment]
error logs at startup
[error-startup.log](https://github.com/survivant/kafkastream-statestore-migrated-to-another-instance/files/6497133/error-startup.log)

After adding a new order
````
    KafkaStreamNumberProcessor-Process Key=6b94baad-5f7d-49a3-a54a-579ba9ab0306  value=Order(orderId=6b94baad-5f7d-49a3-a54a-579ba9ab0306, product=45, orderTimestamp=2021-05-17T22:07:38.298987600Z, status=NEW)
2021-05-17 18:07:38.304  INFO 18012 --- [ntainer#1-0-C-1] c.e.k.consumer.OrderNumberConsumer       : Order consumed (from Number Producer)-> Order(orderId=6b94baad-5f7d-49a3-a54a-579ba9ab0306, product=45, orderTimestamp=2021-05-17T22:07:38.298987600Z, status=NEW)
    KafkaStreamNumberProcessor-Process Key=c8e9d8fb-d116-4910-acf4-a829006a30bd  value=Order(orderId=c8e9d8fb-d116-4910-acf4-a829006a30bd, product=46, orderTimestamp=2021-05-17T22:07:41.294370100Z, status=NEW)
2021-05-17 18:07:41.298  INFO 18012 --- [ntainer#1-0-C-1] c.e.k.consumer.OrderNumberConsumer       : Order consumed (from Number Producer)-> Order(orderId=c8e9d8fb-d116-4910-acf4-a829006a30bd, product=46, orderTimestamp=2021-05-17T22:07:41.294370100Z, status=NEW)
2021-05-17 18:07:42.528  INFO 18012 --- [ntainer#0-0-C-1] c.e.k.consumer.OrderConsumer             : Order consumed (auto ack)-> Order(orderId=string, product=xxx, orderTimestamp=string, status=new)
    KafkaStreamOrderProcessor Key=string  value=Order(orderId=string, product=xxx, orderTimestamp=string, status=new)
KafkaStreamOrderProcessorWindow Key=string  value=Order(orderId=string, product=xxx, orderTimestamp=string, status=new)
2021-05-17 18:07:42.718  INFO 18012 --- [-StreamThread-1] o.a.k.s.s.i.RocksDBTimestampedStore      : Opening store countsWindow.1621252800000 in regular mode
    KafkaStreamNumberProcessor-Process Key=f0ac8621-d14f-458a-8100-3331363aba35  value=Order(orderId=f0ac8621-d14f-458a-8100-3331363aba35, product=47, orderTimestamp=2021-05-17T22:07:44.309137700Z, status=NEW)
2021-05-17 18:07:44.313  INFO 18012 --- [ntainer#1-0-C-1] c.e.k.consumer.OrderNumberConsumer       : Order consumed (from Number Producer)-> Order(orderId=f0ac8621-d14f-458a-8100-3331363aba35, product=47, orderTimestamp=2021-05-17T22:07:44.309137700Z, status=NEW)
    KafkaStreamNumberProcessor-Process Key=ea95d9b9-05e7-4203-886f-03785e25247f  value=Order(orderId=ea95d9b9-05e7-4203-886f-03785e25247f, product=48, orderTimestamp=2021-05-17T22:07:47.290588600Z, status=NEW)
2021-05-17 18:07:47.295  INFO 18012 --- [ntainer#1-0-C-1] c.e.k.consumer.OrderNumberConsumer       : Order consumed (from Number Producer)-> Order(orderId=ea95d9b9-05e7-4203-886f-03785e25247f, product=48, orderTimestamp=2021-05-17T22:07:47.290588600Z, status=NEW)
    KafkaStreamNumberProcessor-Process Key=ee9c4c55-37c7-455c-a66c-3f82ffd94783  value=Order(orderId=ee9c4c55-37c7-455c-a66c-3f82ffd94783, product=49, orderTimestamp=2021-05-17T22:07:50.308575200Z, status=NEW)
2021-05-17 18:07:50.314  INFO 18012 --- [ntainer#1-0-C-1] c.e.k.consumer.OrderNumberConsumer       : Order consumed (from Number Producer)-> Order(orderId=ee9c4c55-37c7-455c-a66c-3f82ffd94783, product=49, orderTimestamp=2021-05-17T22:07:50.308575200Z, status=NEW)
    KafkaStreamNumberProcessor-Process Key=cc8bd800-0c49-450d-ba16-0053e43b43cf  value=Order(orderId=cc8bd800-0c49-450d-ba16-0053e43b43cf, product=50, orderTimestamp=2021-05-17T22:07:53.308780800Z, status=NEW)
2021-05-17 18:07:53.312  INFO 18012 --- [ntainer#1-0-C-1] c.e.k.consumer.OrderNumberConsumer       : Order consumed (from Number Producer)-> Order(orderId=cc8bd800-0c49-450d-ba16-0053e43b43cf, product=50, orderTimestamp=2021-05-17T22:07:53.308780800Z, status=NEW)
2021-05-17 18:07:56.296  INFO 18012 --- [ntainer#1-0-C-1] c.e.k.consumer.OrderNumberConsumer       : Order consumed (from Number Producer)-> Order(orderId=f672081d-7a03-4fe5-9a6f-68a0b8f4216a, product=51, orderTimestamp=2021-05-17T22:07:56.291020900Z, status=NEW)
    KafkaStreamNumberProcessor-Process Key=f672081d-7a03-4fe5-9a6f-68a0b8f4216a  value=Order(orderId=f672081d-7a03-4fe5-9a6f-68a0b8f4216a, product=51, orderTimestamp=2021-05-17T22:07:56.291020900Z, status=NEW)
````

**Comment by survivant** [comment]
````
2021-05-17 18:05:22.384  WARN 18012 --- [-StreamThread-1] org.apache.kafka.clients.NetworkClient   : [Consumer clientId=OrderStreamProcessorWindow-StreamThread-1-consumer, groupId=OrderStreamProcessorWindow] Error while fetching metadata with correlation id 32 : {orders-window=UNKNOWN_TOPIC_OR_PARTITION, OrderStreamProcessorWindow-countsWindow-repartition=UNKNOWN_TOPIC_OR_PARTITION}
2021-05-17 18:05:22.392 ERROR 18012 --- [-StreamThread-1] o.a.k.s.p.i.StreamsPartitionAssignor     : stream-thread [OrderStreamProcessorWindow-StreamThread-1-consumer] Source topic orders-window is missing/unknown during rebalance, please make sure all source topics have been pre-created before starting the Streams application. Returning error INCOMPLETE_SOURCE_TOPIC_METADATA
2021-05-17 18:05:22.392 ERROR 18012 --- [-StreamThread-1] o.a.k.s.p.i.StreamsPartitionAssignor     : stream-thread [OrderStreamProcessor2-StreamThread-1-consumer] Source topic orders is missing/unknown during rebalance, please make sure all source topics have been pre-created before starting the Streams application. Returning error INCOMPLETE_SOURCE_TOPIC_METADATA
````

I have this
````
@Bean
    public NewTopic orderStreamProcessorWindowTopic() {
        return TopicBuilder.name(inputTopicWindow)
                .partitions(1)
                .replicas(1)
                //.config("retention.ms", "60000")
                //config("segment.ms", "60000")
                .build();
    }
````
